import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ThemeProvider } from '@mui/material'

import Navigation from '../component/Navigation'
import { MobileNavigation } from '../component/Navigation'
// import Header from './sections/Header'
import Header from '../sections/Header'
import Main from '../sections/Main'
import Feature from '../sections/Features'
import CTA from '../sections/Cta'
import Footer from '../sections/Footer'

import { theme } from '../theme'

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navigation />
        <MobileNavigation/>
        <Header />
        <Feature/>
        <Main />

        <CTA />
        <Footer/>

     
      </div>
      </ThemeProvider>
  )
}
